### ISSUE TITLE
Where can I find better dictionary?

### ISSUE THREAD

**Issue by PasaOpasen** [AzamRabiee/Persian_G2P#1]
Where can I find larger dictionary like tihu?

**Comment by AzamRabiee** [comment]
You can directly contact Mostafa (mostafa.sedaghat[at]gmail[dot]com; https://github.com/b00f). He may share the full dictionary with you.
Also, I have found that Asr-Gooyesh (http://asr-gooyesh.com/en/) have even more complete dictionary. Please let me know if further info is needed.

**Comment by git-ram** [comment]
Do I need to contact asr-gooyesh to receive the dictionary or is it somewhere on their website to download?
Thanks for your help

**Comment by AzamRabiee** [comment]
You may need a negotiation with Asr_Gooyesh. I don't know any publicly available lexicon at this moment.

**Comment by git-ram** [comment]
Understood. Thank you so much.
