### ISSUE TITLE
tihudict.dict missing

### ISSUE THREAD

**Issue by git-ram** [AzamRabiee/Persian_G2P#2]
Running g2p.py gives an error on line 51 about tihudict.dict file missing.  I tried the tihu.demo.dict from the tihu repo but the output does not look as the default output that you have mentioned in the README. Is there a way I can get the tihudict.dict file you used?

**Comment by AzamRabiee** [comment]
Thanks for your interest in Persian Language.
You are right. 
For the complete dictionary, please ask Mostafa Sedaghat Joo (https://github.com/b00f).

**Comment by git-ram** [comment]
Persian is a lovely language to study. I appreciate your help.
